### ISSUE TITLE
pip installing the older version.

### ISSUE THREAD

**Issue by siddarth-patil** [lc5415/raceplotly#12]
While trying to install `raceplotly` using the pip command. It installed the old version of raceplotly instead of the new one. 
Code used: `pip install raceplotly`
Output: 

> Requirement already satisfied: raceplotly in /usr/local/lib/python3.6/dist-packages (0.1.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from raceplotly) (1.1.5)
Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (from raceplotly) (4.4.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas->raceplotly) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->raceplotly) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas->raceplotly) (2.8.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from plotly->raceplotly) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly->raceplotly) (1.3.3)

As the new version is v.0.1.5, I tried to update the library using the below command.
`pip install -U raceplotly`

The output was:

> Requirement already up-to-date: raceplotly in /usr/local/lib/python3.6/dist-packages (0.1.4)
Requirement already satisfied, skipping upgrade: pandas in /usr/local/lib/python3.6/dist-packages (from raceplotly) (1.1.5)
Requirement already satisfied, skipping upgrade: plotly in /usr/local/lib/python3.6/dist-packages (from raceplotly) (4.4.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->raceplotly) (2018.9)
Requirement already satisfied, skipping upgrade: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas->raceplotly) (1.19.5)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas->raceplotly) (2.8.1)
Requirement already satisfied, skipping upgrade: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly->raceplotly) (1.3.3)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.6/dist-packages (from plotly->raceplotly) (1.15.0)

Why is the new version not being installed? Please help.

**Comment by lucharo** [comment]
Mmmm, that's weird. Are you working in a virtual environment? You can also try running `pip install raceplotly==0.1.5`

**Comment by siddarth-patil** [comment]
I guess the issue is with GoogleColab. When I tried to use the code `pip install raceplotly==0.1.5` it gave the below error:

> ERROR: Could not find a version that satisfies the requirement raceplotly==0.1.5 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4)
ERROR: No matching distribution found for raceplotly==0.1.5

Till now I was trying to code on GoogleColab. And therefore was facing the issue. 

But when I tried to install raceplotly on my local it worked perfectly fine as expected. 

Any idea why GoogleColab is behaving like this?

**Comment by lucharo** [comment]
My guess is that google colab may be running `python 3.6`, try running `!python -V` in a GC cell

**Comment by siddarth-patil** [comment]
This makes sense now. GC is running `Python 3.6.9`. And that is the reason that the new version is not getting installed. So I have to update the python version and it would work fine then. Thanks for the help.

**Comment by lucharo** [comment]
Yes, that should be it, I don't know how updating python works in GC though! Good luck
