### ISSUE TITLE
No export to gif or html function

### ISSUE THREAD

**Issue by shuaiwang88** [lc5415/raceplotly#17]
Any solutions?

**Comment by siddarth-patil** [comment]
I think what you are looking for is [this](https://www.screentogif.com/). This is an easy tool to save the plots into GIFs. Hope this helps.

**Comment by shuaiwang88** [comment]
I am more interesting in saving the plot into a html, so other people can view the plots on their browser.

**Comment by shuaiwang88** [comment]
nvm. I am stupid. 
this helped:
https://plotly.com/python/interactive-html-export/
