### ISSUE TITLE
item_color - AttributeError: 'str' object has no attribute 'keys'

### ISSUE THREAD

**Issue by belisards** [lc5415/raceplotly#19]
I'm trying to define the parameter **item_color** exactly as the documentation describes (creating a dictionary and then using it to map the categories values to colours in a new column). Still, it always leads to the following error:

 **AttributeError: 'str' object has no attribute 'keys'**

I'm using Python 3.10.6.

**Comment by siddarth-patil** [comment]
Thanks for pointing it out. I have opened a #20 PR. Should fix the issue.

**Comment by lucharo** [comment]
is this closed @siddarth-patil??

**Comment by siddarth-patil** [comment]
@lucharo Yes. It can be closed now. I have fixed the error.

**Comment by siddarth-patil** [comment]
@lucharo Yes. It can be closed now.

**Comment by lucharo** [comment]
Sweet, thank you @siddarth-patil
